added workflow_run trigger

diff --git a/.github/workflows/deploy-after-tests.yml b/.github/workflows/deploy-after-tests.yml
--- a/.github/workflows/deploy-after-tests.yml
+++ b/.github/workflows/deploy-after-tests.yml
@@ -10,11 +10,12 @@ jobs:
         steps:
             - name: condition to fulfill
               run: |
-              if [ "${{ github.event.workflow_run.conclusion }}" == 'success' ]; then
-                echo "The workflow is running successfully"
-              else
-                echo "Trigger Workflow failed"
-                exit 1
-              fi
+            
+                if [ "${{ github.event.workflow_run.conclusion }}" == 'success' ]; then
+                    echo "The workflow is running successfully"
+                else
+                    echo "Trigger Workflow failed"
+                    exit 1
+                fi
             - name: deploy-tests 
               run: echo "This message is printed when workflow is triggered after successfull completion of another workflow"
